---
# tasks file for win_branch_server
- name: Install file server features
  ansible.windows.win_feature:
    name:
    - FS-FileServer
    - FS-Resource-Manager
    state: present
  notify: Reboot when feature installed

- name: Create department folders
  ansible.windows.win_file:
    path: "{{ top_level_share }}{{ item }}"
    state: directory
  loop:
    - "{{ group_names.splitlines() }}"

- name: Add Users ACL
  ansible.windows.win_acl:
    path: "{{ top_level_share }}{{ item }}"
    user: "{{ ad_domain }}\\{{ item }}"
    rights: Read,Write,Modify,Delete
    type: allow
    state: present
    inherit: ContainerInherit, ObjectInherit
  loop:
    - "{{ group_names.splitlines() }}"

- name: Add management ACL
  ansible.windows.win_acl:
    path: "{{ top_level_share }}"
    user: "{{ ad_domain }}\\IT"
    rights: FullControl
    type: allow
    state: present
    inherit: ContainerInherit, ObjectInherit

- name: Create SMB share
  ansible.windows.win_share:
    name: branch_share
    description: standard branch share
    path: "{{ top_level_share }}"
    list: false
    full: everyone
